### ISSUE TITLE
Prepare **rgrass7** release with everything deprecated

### ISSUE THREAD

**Issue by rsbivand** [rsbivand/rgrass#67]
Hi @VLucet @hellik @florisvdh @veroandreo : if you could have a look at the `rgrass7` branch - I've prepared `0.2-11` deprecating everything as we discussed earlier. Is this OK?

**Comment by veroandreo** [comment]
Hi @rsbivand, it seems ok to me. AFAIU, all functions receive the deprecated warning and those that changed names, make it explicit, right? Will this one be then the last `rgrass7`?

**Comment by hellik** [comment]
@rsbivand it looks good.

**Comment by florisvdh** [comment]
Looks good indeed (have tried some locally) – the deprecation will be very obvious :+1:. Thanks a lot for doing all this work.

Assuming that the intention was to explicitly deprecate all exported functions, then some exported functions (below) aren't yet deprecated. Maybe it's a deliberate choice, since these are no primary functions.

```
gmeta2grd
getXMLencoding
setXMLencoding
getLocationProj
get.GIS_LOCK
set.GIS_LOCK
unset.GIS_LOCK
unlink_.gislock
remove_GISRC
```

In the `rgrass7` branch, following files are clearly outdated, so it also seems appropriate to:

- drop `.github/CONTRIBUTING.md` (in the `rgrass7` branch it's not up to date anyway)
- update `README.md` (perhaps just displaying the new description _Deprecated interpreted interface between 'GRASS' geographical information system and R. Transition to new package 'rgrass'._)

Both files are visible in the GitHub repo when switched to the `rgrass7` branch: https://github.com/rsbivand/rgrass/tree/rgrass7.

And in the `main` branch (this does not apply to the next **rgrass7** release), the last two bullets of `.github/CONTRIBUTING.md` – about the `rgrass7` branch and **rgrass7** package respectively – will need to be simplified/updated after the **rgrass7** release.

**Comment by rsbivand** [comment]
Thanks, I'll add these and deprecate the missed monor exported functiond. The current state is now on CRAN, so some other corrections msy be needed if users respond.
